### ISSUE TITLE
Improper channel resync after reconnect

### ISSUE THREAD

**Issue by tehmaze** [seveas/ubot#2]
The channel cache isn't re-synced properly after a reconnect, the following exception is thrown when the first `JOIN` is sent out:

```
Error in sys.excepthook:
TypeError: 'NoneType' object is not callable

Original exception was:
Traceback (most recent call last):
  File "/home/ubot/src/ubot/lib/ubot/irc.py", line 90, in incoming
    self.message_handler(msg)
  File "/home/ubot/src/ubot/lib/ubot/bot.py", line 161, in handle_message
    getattr(self, h)(message)
  File "/home/ubot/src/ubot/lib/ubot/bot.py", line 349, in handle_join
    self.channels[msg.target].nicks.append(msg.nick)
KeyError: u'dev'
```

**Comment by seveas** [comment]
The channel cache is wiped on disconnect. The first join one would usually see for a channel is the bot itself joining the channel, this creates the entry in the channel cache. The code above is called when others join the channel. Did you receive join messages out of order? I also notice that the channel name is 'dev', not '#dev' or '&dev', what is the IRC server you use?
